env:
  browser: true
  es2020: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 11
  sourceType: module
ignorePatterns: ["dist/*","node_modules/*"]
rules: {
  "no-console": "off",
  "import/extensions": "off",
}
